services:
  - type: web
    name: experiment-report-summarizer
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-tur poppler-utils
      pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: SUMMARY_FOLDER
        value: /tmp/summaries
