services:
  - type: web
    name: experiment-report-summarizer
    runtime: docker
    region: frankfurt
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract
      - key: POPPLER_PATH
        value: /usr/bin
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: SUMMARY_FOLDER
        value: /tmp/summaries
